import Database.KoneksiDatabase;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Cetak_Laporan extends javax.swing.JInternalFrame {
    ResultSet rs;
    KoneksiDatabase con;
    public String lap;
    /**
     * Creates new form Cetak_Laporan
     */
    public Cetak_Laporan() {
        initComponents();
        con =new KoneksiDatabase(new Database.Parameter().HOST_DB,new Database.Parameter().USERNAME_DB,new Database.Parameter().PASSWORD_DB);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_laporan = new javax.swing.JTable();
        jDate2 = new com.toedter.calendar.JDateChooser();
        jDate1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonGlass1 = new usu.widget.ButtonGlass();
        btn_data = new usu.widget.ButtonGlass();
        btn_laporan = new usu.widget.ButtonGlass();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_laporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal Peminjaman", "Tanggal Kembali", "Peminjam", "Nopol", "Harga Sewa", "Lama Pinjam", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel_laporan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 940, 450));
        getContentPane().add(jDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 150, -1));
        getContentPane().add(jDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LAPORAN DATA TRANSAKSI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        lbl_total.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(153, 0, 0));
        lbl_total.setText("Total");
        getContentPane().add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 360, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dari Tanggal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sampai Tanggal");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TOTAL TRANSAKSI :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rp");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, 40));

        buttonGlass1.setForeground(new java.awt.Color(255, 255, 255));
        buttonGlass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calculator.png"))); // NOI18N
        buttonGlass1.setText("Hitung Total");
        buttonGlass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGlass1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonGlass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 140, 50));

        btn_data.setForeground(new java.awt.Color(255, 255, 255));
        btn_data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_lense.png"))); // NOI18N
        btn_data.setText("Cari Data");
        btn_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataActionPerformed(evt);
            }
        });
        getContentPane().add(btn_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 140, 50));

        btn_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/laporan.png"))); // NOI18N
        btn_laporan.setText("Cetak Laporan");
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 220, 110));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bgb.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        cetak();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void btn_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataActionPerformed
        java.util.Date tgl = (java.util.Date) this.jDate1.getDate();
        java.util.Date tgl1 = (java.util.Date) this.jDate2.getDate();
        if(new java.sql.Date(tgl.getTime()).toString().isEmpty() && new java.sql.Date(tgl.getTime()).toString().isEmpty()){
            JOptionPane.showMessageDialog(this, "Tanggal data pencarian masih kosong");
        }else{
            try {
                SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                String a = new java.sql.Date(tgl.getTime()).toString();
                String b = new java.sql.Date(tgl1.getTime()).toString();
                String kolom[] = { "tgl_peminjaman", "tgl_kembali","peminjam", "nopol", "harga", "lama", "total"};
                rs=con.querySelect(kolom ,"tb_laporan"," DATE_FORMAT(tgl_peminjaman,'%Y-%m-%d')>='"+a+"' AND DATE_FORMAT(tgl_peminjaman,'%Y-%m-%d')<= '"+b+"' "); 
                
                tabel_laporan.setModel(new Database.ResultSetTable(rs));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Pencarian Error");
            }
        }
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dataActionPerformed

    private void buttonGlass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGlass1ActionPerformed
        hitungtotal();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGlass1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.ButtonGlass btn_data;
    private usu.widget.ButtonGlass btn_laporan;
    private usu.widget.ButtonGlass buttonGlass1;
    private com.toedter.calendar.JDateChooser jDate1;
    private com.toedter.calendar.JDateChooser jDate2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable tabel_laporan;
    // End of variables declaration//GEN-END:variables

    public void cetak() {
       clear();
       SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd"); 
       String a = String.valueOf(format.format(jDate1.getDate()));
       String b = String.valueOf(format.format(jDate2.getDate())); 
       try{
            rs = con.eksekusiQuery("select SUM(total) from tb_laporan where DATE_FORMAT(tgl_peminjaman,'%Y-%m-%d')>='"+a+"' AND DATE_FORMAT(tgl_peminjaman,'%Y-%m-%d')<= '"+b+"' ");
                while(rs.next()){
                    lap=rs.getString(1);
                }
                try{
                    tabel_laporan.print(JTable.PrintMode.FIT_WIDTH, new MessageFormat("Data Transaksi dengan Total : Rp. "+lap), null);
                }catch(PrinterException ep){
                JOptionPane.showMessageDialog(null, ep);
            }
       }catch (SQLException es){
            JOptionPane.showMessageDialog(rootPane, "Error "+es);
       }
    }

    public void hitungtotal() {
       SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd"); 
       String a = String.valueOf(format.format(jDate1.getDate()));
       String b = String.valueOf(format.format(jDate2.getDate())); 
       try{
            rs = con.eksekusiQuery("select SUM(total) from tb_laporan where DATE_FORMAT(tgl_peminjaman,'%Y-%m-%d')>='"+a+"' AND DATE_FORMAT(tgl_peminjaman,'%Y-%m-%d')<= '"+b+"' ");
                while(rs.next()){
                    lap=rs.getString(1);
                    lbl_total.setText(lap);
                }                
        }catch (SQLException es){
            JOptionPane.showMessageDialog(rootPane, "Error "+es);
        }
    }
    
    public void clear(){
        lbl_total.setText("");
    }


}
