import javax.swing.ImageIcon;
/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    //    setExtendedState(MAXIMIZED_BOTH);
        setIconImage(new ImageIcon(getClass().getResource("image/himatif.png")).getImage());
        btn_logout.setVisible(false);
        btn_addcar.setVisible(false);
        btn_formPeminjam.setVisible(false);
        btn_adduser.setVisible(false);
        btn_formPengembalian.setVisible(false);
        btn_cetak.setVisible(false);
        btn_about.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new BG();
        btn_formPeminjam = new usu.widget.ButtonGlass();
        btn_adduser = new usu.widget.ButtonGlass();
        btn_login = new usu.widget.ButtonGlass();
        btn_logout = new usu.widget.ButtonGlass();
        btn_exit = new usu.widget.ButtonGlass();
        btn_formPengembalian = new usu.widget.ButtonGlass();
        btn_addcar = new usu.widget.ButtonGlass();
        btn_about = new usu.widget.ButtonGlass();
        btn_cetak = new usu.widget.ButtonGlass();
        btn_hargasewa = new usu.widget.ButtonGlass();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LA-TAKHSAR RENT CARS 1.1");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1220, 768));

        btn_formPeminjam.setForeground(new java.awt.Color(255, 255, 255));
        btn_formPeminjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pinjam.png"))); // NOI18N
        btn_formPeminjam.setText("PINJAM MOBIL");
        btn_formPeminjam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_formPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formPeminjamActionPerformed(evt);
            }
        });
        getContentPane().add(btn_formPeminjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, 80));

        btn_adduser.setForeground(new java.awt.Color(255, 255, 255));
        btn_adduser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add_user.png"))); // NOI18N
        btn_adduser.setText("ADD USER");
        btn_adduser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_adduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adduserActionPerformed(evt);
            }
        });
        getContentPane().add(btn_adduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 210, 80));

        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LI.png"))); // NOI18N
        btn_login.setText("LOG IN");
        btn_login.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 210, 80));

        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log_out.png"))); // NOI18N
        btn_logout.setText("LOG OUT");
        btn_logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 210, 80));

        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Off.png"))); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 210, 80));

        btn_formPengembalian.setForeground(new java.awt.Color(255, 255, 255));
        btn_formPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kembali.png"))); // NOI18N
        btn_formPengembalian.setText("PENGEMBALIAN MOBIL");
        btn_formPengembalian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_formPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formPengembalianActionPerformed(evt);
            }
        });
        getContentPane().add(btn_formPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 210, 80));

        btn_addcar.setForeground(new java.awt.Color(255, 255, 255));
        btn_addcar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add_mobil1.png"))); // NOI18N
        btn_addcar.setText("ADD MOBIL");
        btn_addcar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_addcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_addcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 210, 80));

        btn_about.setForeground(new java.awt.Color(255, 255, 255));
        btn_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/about.png"))); // NOI18N
        btn_about.setText("ABOUT");
        btn_about.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 210, 80));

        btn_cetak.setForeground(new java.awt.Color(255, 255, 255));
        btn_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/laporan.png"))); // NOI18N
        btn_cetak.setText("CETAK LAPORAN");
        btn_cetak.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 210, 80));

        btn_hargasewa.setForeground(new java.awt.Color(255, 255, 255));
        btn_hargasewa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hargasewa.png"))); // NOI18N
        btn_hargasewa.setText("HARGA SEWA");
        btn_hargasewa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_hargasewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hargasewaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hargasewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, 70));

        panelGlass1.setWarna(new java.awt.Color(51, 51, 255));
        getContentPane().add(panelGlass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 250, 660));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bb1.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(323, 768));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adduserActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Add_User fm = new Add_User();
        fm.setVisible(true);
        jDesktopPane1.add(fm);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_adduserActionPerformed

    private void btn_formPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formPeminjamActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Form_Peminjam fm = new Form_Peminjam();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
    }//GEN-LAST:event_btn_formPeminjamActionPerformed

    private void btn_addcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addcarActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Add_Car fm = new Add_Car();
        fm.setVisible(true);
        jDesktopPane1.add(fm);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addcarActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        //     jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        dispose();
        Login fm = new Login();
        fm.setVisible(true);
        //jDesktopPane1.add(fm);


    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_formPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formPengembalianActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Form_Pengembalian fm = new Form_Pengembalian();
        fm.setVisible(true);
        jDesktopPane1.add(fm);// TODO add your handling code here:
    }//GEN-LAST:event_btn_formPengembalianActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        btn_login.setVisible(true);
        btn_hargasewa.setVisible(true);
        btn_logout.setVisible(false);
        btn_logout.setVisible(false);
        btn_addcar.setVisible(false);
        btn_formPeminjam.setVisible(false);
        btn_adduser.setVisible(false);
        btn_formPengembalian.setVisible(false);
        btn_cetak.setVisible(false);
        btn_about.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aboutActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        About fm = new About();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
    }//GEN-LAST:event_btn_aboutActionPerformed

    private void btn_hargasewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hargasewaActionPerformed
        jDesktopPane1.repaint();
        dispose();
        Harga_Sewa h = new Harga_Sewa();
        h.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_hargasewaActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Cetak_Laporan fm = new Cetak_Laporan();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    public void owner() {

        btn_addcar.setVisible(true);
        btn_formPeminjam.setVisible(true);
        btn_adduser.setVisible(true);
        btn_logout.setVisible(true);
        btn_login.setVisible(false);
        btn_hargasewa.setVisible(false);
        btn_formPengembalian.setVisible(true);
        btn_cetak.setVisible(true);
        btn_about.setVisible(false);


    }

    public void user() {
        btn_addcar.setVisible(true);
        btn_formPeminjam.setVisible(true);
        btn_adduser.setVisible(false);
        btn_logout.setVisible(true);
        btn_hargasewa.setVisible(false);
        btn_login.setVisible(false);
        btn_formPengembalian.setVisible(true);
        btn_cetak.setVisible(true);
        btn_about.setVisible(false);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static usu.widget.ButtonGlass btn_about;
    public static usu.widget.ButtonGlass btn_addcar;
    public static usu.widget.ButtonGlass btn_adduser;
    public static usu.widget.ButtonGlass btn_cetak;
    public static usu.widget.ButtonGlass btn_exit;
    public static usu.widget.ButtonGlass btn_formPeminjam;
    public static usu.widget.ButtonGlass btn_formPengembalian;
    public static usu.widget.ButtonGlass btn_hargasewa;
    public static usu.widget.ButtonGlass btn_login;
    public static usu.widget.ButtonGlass btn_logout;
    public static javax.swing.JDesktopPane jDesktopPane1;
    public static javax.swing.JLabel jLabel1;
    public static usu.widget.glass.PanelGlass panelGlass1;
    // End of variables declaration//GEN-END:variables
}
